POST http://localhost:8080/api/users
Content-Type: application/json

{
  "id": null,
  "name": "Géraldine Chaton",
  "email": "geraldine.chaton@example.com",
  "password": "password1234",
  "userBalance": 2000.00
  }